# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f3182d6a3c422b3d45ab7d8f1d7876b737d77754a9ee6632063efaabd9412c89373cb5afbb59efca38408bd4c4b796bd034dc5508242b89c86063992b9a744

test:
  secret_key_base: 5c993e62990eee09f7f4c025991ef14d8b33bf528e92b7f31a734d8285584ac052c267ed8cffd7eced7386e3c20f62d81df9d97fa8fc4c52d9dc3c12ca18d159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
